### ISSUE TITLE
[Feature Request] Ignore non existent table columns?

### ISSUE THREAD

**Issue by FloKnapp** [tflori/orm#31]
(!) Feature Request

Hi there,

i'm implementing a new form builder with all this fancy stuff like password and password_repeat fields. To minimize dependencies and make it maximum generic i'm pushing the whole form data as an array into the constructor of the entity class.

Now (of course and correct) your validation logic complains about the non existent field 'password_repeat'.

I found a solution within my implementation but it isn't beatiful. Is there any possibility that this check for existent columns can be bypassed? Maybe with an optional parameter in the constructor which is enabled by default  but can bypass this check by setting it to 'false'?

I think this can be very helpful for others too and it shouldn't have a huge impact or causing massive development effort.

I would appreciate that very much if you can make this possible! :-)

Thank you very much in advance!

Greetings,

Flo

**Comment by tflori** [comment]
here it begins to get a lot of code :) 

ok not that much. there should be a way to get the table definition in ansi sql (so that every driver understands it). than we can create a more definitive function `fill(array $data, EntityManager $em, bool $ignoreUnknown = false)`. this function than can query `DESCRIBE table`.. 

here becomes the next question to get interesting: validate column types? log warnings for unknown types (you can define new types at least in postgres).. 

but if you want to implement it I would be very thankful. for now without validation maybe.. 

I'm in Venice the next days. So don't calculate with a merge the next days :)

**Comment by tflori** [comment]
I just realized there is no such standard to describe a table. It is very annoying.

To go deeper in this direction we need to abstract the database communication with a database abstraction layer. I decided to put this to version 1.2 as we discussed.

These steps are necessary first:

1. #32
2. #33

**Comment by FloKnapp** [comment]
👍 Confirmed and works like a charm. Further improvements are also done, especially the EntityManager isn't mandatory any more within the 'save'-method. Great work mate!

**Comment by tflori** [comment]
ok, thanks. merged to 1.2 - you can install 1.2.x-dev. I'll tag 1.2 with 1.2.0-alpha1 later so `tflori/orm@alpha` should work too then.
